In [11]:
import numpy as np

In [16]:
a=np.random.randint(2, 10, size=(1,5))
arlist = a.tolist()
print(arlist)

[[7, 5, 8, 8, 7]]


In [18]:
m = np.arange(6).reshape(2,3)
result =  np.trace(m)
print(result)

4


In [20]:
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])

print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))


Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [31]:
a,b=np.random.randint(1,19, size=(2,5))
print(a)
print(b)
c= a+b
print("the result:")
print(c)

[11 12 18  4 16]
[ 4  5  7  3 16]
the result:
[15 17 25  7 32]


In [38]:
x=np.random.randint(1,15,size=(2,5))
y=x - x.mean(axis=1, keepdims=True)

print(y)

[[ 5.8 -1.2  1.8 -4.2 -2.2]
 [-6.6  5.4  3.4  0.4 -2.6]]
